//! poincare_2I_holonomy — Poincare Tier 2 live receipt (the crown jewel).
//!
//! The Poincare homology sphere Sigma = S^3/2I has H_* = (Z,0,0,Z) — Betti
//! (1,0,0,1), IDENTICAL to S^3 — so every homology-type invariant is BLIND to
//! it. Yet pi_1(Sigma) = 2I, the binary icosahedral group of order 120. 2I is
//! PERFECT (abelianization trivial), so even an abelianizing homotopy invariant
//! (gigi's Phase-1 PI_1 = beta_1) is blind. The ONLY thing that sees Sigma != S^3
//! is the NON-ABELIAN SU(2) holonomy.
//!
//! This example demonstrates that live, entirely through gigi's own group math:
//!   1. Register the flat SU(2) connection realizing pi_1(Sigma)=2I: identity on
//!      every edge except two 'generator' edges carrying the icosians s, t.
//!   2. Read the generators back through the shipped HOLONOMY AROUND CYCLE EDGES
//!      verb: s (order 6), t (order 10), st (order 4) — the binary/double cover
//!      of the icosahedral (3,5,2). SEES the non-trivial pi_1.
//!   3. Close <s,t> under gigi's GroupElement::compose (the same product walk_loop
//!      uses per link) -> order 120. The holonomy group IS 2I.  [holonomy SEES]
//!   4. Close the commutator subgroup [G,G] under compose -> also 120 = |G|, so G
//!      is perfect => abelianization trivial => H_1 = 0. This is WHY homology and
//!      abelianized-pi_1 are blind.                                 [homology BLIND]
//!   Plus the S^3 control: identity field -> holonomy trivial, group order 1.
//!
//! The generators are input construction (like the Tier-1 lens twist); every
//! GROUP operation (the holonomy walk, the closure, the commutators) is gigi's.
//!
//! Run:
//!   cargo run --release --example poincare_2I_holonomy --features halcyon,gauge,lattice

use std::collections::HashSet;
use std::sync::Arc;

use gigi::engine::Engine;
use gigi::gauge::group_element::GroupElement;
use gigi::gauge::registry as gauge_registry;
use gigi::gauge::{DenseLinkBuffer, GaugeFieldHandle, GaugeFieldInit, Group, SU2GaugeField};
use gigi::lattice::registry as lattice_registry;
use gigi::lattice::Lattice;
use gigi::parser::{execute, parse, ExecResult};
use gigi::types::{Record, Value};

type Q = [f64; 4];

fn declare_cubic(eng: &mut Engine, name: &str, l: usize, d: usize) -> Lattice {
    let gql = format!("LATTICE {name} FROM CUBIC L={l} DIM={d} PERIODIC;");
    let stmt = parse(&gql).expect("parse LATTICE");
    execute(eng, &stmt).expect("exec LATTICE");
    lattice_registry::get(name).expect("lattice registered")
}

/// Identity SU(2) field on `lat` with (edge_id, quaternion) overrides, planted
/// via the public `from_buffer` factory (GQL INIT offers only IDENTITY/HAAR).
fn register_su2(name: &str, lat: &Lattice, overrides: &[(usize, Q)]) {
    let n_edges = lat.n_edges();
    let mut buf = DenseLinkBuffer::new_identity(Group::SU2, n_edges).expect("identity SU2 buffer");
    for &(eid, q) in overrides {
        let base = 4 * eid;
        buf.data[base] = q[0];
        buf.data[base + 1] = q[1];
        buf.data[base + 2] = q[2];
        buf.data[base + 3] = q[3];
    }
    let field = SU2GaugeField::from_buffer(
        name.to_string(),
        lat.name.clone(),
        buf,
        GaugeFieldInit::Identity,
        None,
    );
    let h: Arc<dyn GaugeFieldHandle> = Arc::new(field);
    gauge_registry::register(h);
}

fn run_cycle(eng: &mut Engine, gql: &str) -> Record {
    let stmt = parse(gql).unwrap_or_else(|e| panic!("parse '{gql}': {e}"));
    let res = execute(eng, &stmt).unwrap_or_else(|e| panic!("exec '{gql}': {e}"));
    match res {
        ExecResult::Rows(mut rs) => rs.pop().expect("one row"),
        other => panic!("expected Rows, got {other:?}"),
    }
}
fn ff(r: &Record, k: &str) -> f64 {
    match r.get(k) { Some(Value::Float(v)) => *v, o => panic!("{k} not Float: {o:?}") }
}
fn ii(r: &Record, k: &str) -> i64 {
    match r.get(k) { Some(Value::Integer(v)) => *v, o => panic!("{k} not Integer: {o:?}") }
}

// ── gigi group ops (GroupElement::compose / inverse) driving a finite closure ──

fn ge(q: &Q) -> GroupElement { GroupElement::SU2 { q0: q[0], q1: q[1], q2: q[2], q3: q[3] } }
fn unpack(g: &GroupElement) -> Q {
    match g { GroupElement::SU2 { q0, q1, q2, q3 } => [*q0, *q1, *q2, *q3], _ => unreachable!() }
}
fn key(q: &Q) -> (i64, i64, i64, i64) {
    let r = |x: f64| (x * 1e6).round() as i64;
    (r(q[0]), r(q[1]), r(q[2]), r(q[3]))
}

/// Enumerate the finite group generated by `gens` under gigi's compose.
/// Returns the full element list (capped as a runaway guard).
fn close_group(gens: &[Q]) -> Vec<Q> {
    let ident: Q = [1.0, 0.0, 0.0, 0.0];
    let mut seen: HashSet<(i64, i64, i64, i64)> = HashSet::new();
    let mut elems: Vec<Q> = Vec::new();
    let mut frontier: Vec<Q> = Vec::new();
    for g in std::iter::once(&ident).chain(gens.iter()) {
        if seen.insert(key(g)) { elems.push(*g); frontier.push(*g); }
    }
    while let Some(a) = frontier.pop() {
        for g in gens {
            for prod in [ge(&a).compose(&ge(g)), ge(g).compose(&ge(&a))] {
                let q = unpack(&prod);
                if seen.insert(key(&q)) {
                    elems.push(q);
                    frontier.push(q);
                    if elems.len() > 5000 { return elems; } // guard
                }
            }
        }
    }
    elems
}

/// Order of [G,G] for G = <gens>, via gigi's compose/inverse. Equals |G| iff G is perfect.
fn commutator_subgroup_order(gens: &[Q]) -> usize {
    let g_elems = close_group(gens);
    let mut comms: Vec<Q> = Vec::new();
    for a in &g_elems {
        for b in gens {
            // [a,b] = a b a^-1 b^-1
            let c = ge(a).compose(&ge(b)).compose(&ge(a).inverse()).compose(&ge(b).inverse());
            comms.push(unpack(&c));
        }
    }
    close_group(&comms).len()
}

fn main() {
    gauge_registry::clear();
    lattice_registry::clear();
    let dir = tempfile::tempdir().expect("tempdir");
    let mut eng = Engine::open(dir.path()).expect("engine open");

    // Small cubic host lattice (L=3, DIM=3 -> 81 edges); we only use edges 0 and 1.
    let lat = declare_cubic(&mut eng, "sigma_host", 3, 3);

    // The chosen 2-generator set of 2I (icosian quaternions):
    //   s = 1/2(1,1,1,1)           order 6   (s^3 = -1),  q0 = 1/2   = cos 60
    //   t = 1/2(phi, 1, 1/phi, 0)  order 10  (t^5 = -1),  q0 = phi/2 = cos 36
    //   st                         order 4   ((st)^2=-1), q0 = 0     = cos 90
    let phi = (1.0 + 5.0_f64.sqrt()) / 2.0;
    let inv = phi - 1.0;
    let s: Q = [0.5, 0.5, 0.5, 0.5];
    let t: Q = [phi / 2.0, 0.5, inv / 2.0, 0.0];

    // --- S^3 control: identity field, trivial holonomy, group order 1 ---
    register_su2("sigma_ctrl", &lat, &[]);
    let ctrl = run_cycle(&mut eng, "HOLONOMY sigma_ctrl AROUND CYCLE EDGES (0, 1);");
    let ctrl_order = ii(&ctrl, "order_estimate");
    let ctrl_group = close_group(&[[1.0, 0.0, 0.0, 0.0]]).len();

    // --- Sigma: the 2I connection. Plant s on edge 0, t on edge 1. ---
    gauge_registry::remove("sigma_field");
    register_su2("sigma_field", &lat, &[(0, s), (1, t)]);

    // Read the generators + their product back through the HOLONOMY verb.
    let row_s = run_cycle(&mut eng, "HOLONOMY sigma_field AROUND CYCLE EDGES (0);");
    let row_t = run_cycle(&mut eng, "HOLONOMY sigma_field AROUND CYCLE EDGES (1);");
    let row_st = run_cycle(&mut eng, "HOLONOMY sigma_field AROUND CYCLE EDGES (0, 1);");

    // The holonomy group and its perfection, via gigi's compose.
    let group = close_group(&[s, t]);
    let holonomy_group_order = group.len();
    let comm_order = commutator_subgroup_order(&[s, t]);
    let is_perfect = comm_order == holonomy_group_order;

    let sees = holonomy_group_order == 120;
    let blind_explained = is_perfect; // [G,G]=G  =>  H_1 = 0  =>  homology blind

    // Element-order histogram over the whole holonomy group (the 2I signature).
    let mut order_hist: std::collections::BTreeMap<i64, i64> = std::collections::BTreeMap::new();
    for q in &group {
        // reuse order_estimate semantics via re_trace = q0: order = denom of arccos(q0)/2pi
        let g = *q;
        // small local order finder (compose powers until identity)
        let mut p = g;
        let mut n = 1;
        loop {
            if (p[0] - 1.0).abs() < 1e-6 && p[1].abs() < 1e-6 && p[2].abs() < 1e-6 && p[3].abs() < 1e-6 {
                break;
            }
            p = unpack(&ge(&p).compose(&ge(&g)));
            n += 1;
            if n > 512 { break; }
        }
        *order_hist.entry(n).or_insert(0) += 1;
    }
    let hist_json: Vec<String> = order_hist.iter().map(|(o, c)| format!("\"{o}\":{c}")).collect();

    let gen_row = |name: &str, edges: &str, r: &Record| -> String {
        format!(
            "{{\"loop\":\"{name}\",\"edges\":\"{edges}\",\"q0\":{:.12},\"q1\":{:.12},\
             \"q2\":{:.12},\"q3\":{:.12},\"order_estimate\":{}}}",
            ff(r, "q0"), ff(r, "q1"), ff(r, "q2"), ff(r, "q3"), ii(r, "order_estimate")
        )
    };

    println!(
        "{{\n  \"control_S3\": {{\"holonomy_order_estimate\":{ctrl_order},\"group_order\":{ctrl_group}}},\n  \
         \"generators_via_holonomy_verb\": [\n    {},\n    {},\n    {}\n  ],\n  \
         \"holonomy_group_order\": {holonomy_group_order},\n  \
         \"commutator_subgroup_order\": {comm_order},\n  \
         \"is_perfect\": {is_perfect},\n  \
         \"element_order_histogram\": {{{}}},\n  \
         \"holonomy_SEES_pi1_2I\": {sees},\n  \
         \"homology_BLIND_because_perfect\": {blind_explained}\n}}",
        gen_row("s", "0", &row_s),
        gen_row("t", "1", &row_t),
        gen_row("st", "0,1", &row_st),
        hist_json.join(","),
    );
}
